# Generated by Django 4.0 on 2023-11-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_loc_update',
            field=models.BooleanField(default=False),
        ),
    ]
