# Generated by Django 4.0 on 2023-11-01 07:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_customuser_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.customuser')),
                ('balance', models.FloatField(default=0)),
                ('last_recharge', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'wallet',
                'verbose_name_plural': 'wallets',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Payment Gateway', 'Payment Gateway'), ('Cash', 'Cash'), ('Wallet', 'Wallet')], max_length=50)),
                ('mode', models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit'), ('UPI', 'UPI')], max_length=50)),
                ('category', models.CharField(choices=[('Recharge', 'Recharge'), ('Order', 'Order')], max_length=50)),
                ('amount', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('details', models.CharField(blank=True, max_length=255, null=True)),
                ('collection_due', models.BooleanField(default=False)),
                ('tax', models.FloatField(default=0.0)),
                ('success', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='user.customuser')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.customuser')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'transactions',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(default=0.0)),
                ('total_tax', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Successful', 'Successful'), ('Failed', 'Failed'), ('Refunded', 'Refunded'), ('Partial', 'Partial'), ('Initial Refunded', 'Initial Refunded'), ('Initiated', 'Initiated')], max_length=70)),
                ('payment_ref_no', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('note', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('payment_response_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('transactions', models.ManyToManyField(to='payment.Transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customuser')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('collected_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.customuser')),
                ('transaction', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payment.transaction')),
            ],
            options={
                'verbose_name': 'collection',
                'verbose_name_plural': 'collections',
            },
        ),
    ]
